export enum NotificationType {
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  HACKATHON_REMINDER = 'HACKATHON_REMINDER',
  HACKATHON_REGISTRATION = 'HACKATHON_REGISTRATION',
  IDEA_APPROVED = 'IDEA_APPROVED',
  IDEA_REJECTED = 'IDEA_REJECTED',
}

